### ISSUE TITLE
Add tab for displaying images

### ISSUE THREAD

**Issue by adjn** [BagToad/Zendesk-Link-Collector#54]
Add a third tab for images (Links/Attachments/Images)

It would display a preview of all the images. Clicking on an image should somehow focus the image. 
Possible solutions:
- scroll you to the image
- expand the plugin window to show the whole image
- open the image in a new tab

**Comment by BagToad** [comment]
Related to https://github.com/BagToad/Zendesk-Link-Collector/issues/9

We'll have to consider the best way to handle this between the two ideas. We could start filtering out images from the attachments and put them in their own tab like you suggested - I like the idea of potentially having image preview capabilities with images being in their own tab.

**Comment by BagToad** [comment]
TIL the extension popup [can only be so big](https://stackoverflow.com/questions/8983165/how-can-i-expand-the-popup-window-of-my-chrome-extension). The max size seems too small for most images to be legible 😢 

@adjn should clicking on the image will open it in a new tab or try to open the image in Zendesk's built-in image preview? I'm ready to open a PR if it should open in a new tab, but will need a bit more investigation if it should open in Zendesk's built-in image preview (that will take some experimentation to see if it's even possible).
